sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
addons:
  firefox: "47.0.2"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then npm run deploy; fi
env:
  matrix:
  - CLIENT=selenium:firefox
  - CLIENT=saucelabs:chrome
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
